### ISSUE TITLE
BUG: Textures problem

### ISSUE THREAD

**Issue by mushis** [nQuake/distfiles#13]
Installed a new nQuake Windows client, using the installer.
There is a problem with the textures:
- there is a "textures" folder in the root (containing the textures from the streambot from xantom);
- qw/texture* pak files are missing;

the zip files from the releases page look fine (I mean gpl.zip, non-gpl.zip, even textures.zip) https://github.com/nQuake/distfiles/releases/tag/snapshot

Someone smarter than me can investigate? Is there a log of the installer? I couldn't find it.
 
nQuake.ini: [nquake.zip](https://github.com/nQuake/distfiles/files/8703148/nquake.zip)

![image](https://user-images.githubusercontent.com/3011167/168675008-be2a3531-5ed1-4f47-91f0-b587d6d4a822.png)

edit: I've uploaded nQuake.ini. The mirror section is as follows (url is a 404)
```
[mirror_addresses]
1=https://github.com/nQuake/distfiles/releases/download/snapshot
```

**Comment by eb** [comment]
The nQuake.ini looks fine. It's expected that the URL is 404, because it's just the root of all the dist files.
E.g. https://github.com/nQuake/distfiles/releases/download/snapshot/textures.zip

**Comment by eb** [comment]
I just tried it and it's actually not installing a textures directory in the root and also the texture.pk3 is there.
I think there might be old relicts in your local download folder and they are somehow getting installed.
For a quick fix, delete the download folder before installation (e.g. C:\Users\eb\AppData\Local\nQuake).

**Comment by mushis** [comment]
on the other day, when I tried, I have removed the local/nQuake folder.
I've just tried again (and removed the folder once again), and the problem persists.
looks like its my PC problem. dunno what. 

I guess this can be closed, unless someone wants to try
