### ISSUE TITLE
add locs to sv-maps.zip

### ISSUE THREAD

**Issue by mushis** [nQuake/distfiles#4]
locs should be added to sv-maps.zip
many times the client don't have a loc for a specific map. the usual thing to happen, is some kind soul say "ill send them to you in discord".
there's a better way.
if the server has the locs in the locs folder, clients can use an alias to download it.

bind  k             "download locs/$mapname.loc;loadloc $mapname.loc"
(this alias/ bind would be added to nquake default.cfg)

the map locs should be placed in sv-maps.zip. ideally, ALL the locs for all the maps. edit: not so sure anymore.

**Comment by eb** [comment]
The loc files belong actually in sv-non-gpl.zip and I've updated them a while ago.
