### ISSUE TITLE
ezquake crash on macosx

### ISSUE THREAD

**Issue by dill0wn** [nQuake/distfiles#8]
I'm not sure if this is an issue with the app itself or the installation process. Here are my crashlogs.

[ezquake-crash-macos-12.1.log](https://github.com/nQuake/distfiles/files/7815578/ezquake-crash-macos-12.1.log)

**Comment by dill0wn** [comment]
I just confirmed that manually downloading the [latest ezquake](https://github.com/ezQuake/ezquake-source/releases/download/3.2.3/ezquake-osx10.15.5-xcode11.6-3.2.3-full.zip) from http://www.ezquake.com/ and placing it in the nQuake-created directory works fine. So either the executable bundled by nQuake is old, or macOS is doing something screwy when manually performing steps and the script needs to replicate it.

**Comment by BLooD-DoG** [comment]
Some changes were made to the MacOS files. Is this still an issue or can it be closed?

**Comment by BLooD-DoG** [comment]
Several people have reported success with nQuake for MacOS since changes were made a while ago. Closing for now.
