### ISSUE TITLE
Quick installers don't work (can't download qsw106 over http)

### ISSUE THREAD

**Issue by dsandler** [nQuake/distfiles#9]
STEPS TO REPRODUCE:

1. Download the macosx or linux install scripts from nquake.com
2. Run

OBSERVED:

```
=== Downloading ===
Downloading Quake Shareware...
>>> curl -o qsw106.zip -O http://github.com/nQuake/distfiles/releases/download/snapshot/qsw106.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

>>> ls -l macosx.zip
ls: macosx.zip: No such file or directory
Some distribution files failed to download. Better luck next time. Exiting.
```

(in the transcript above I added `>>>` to indicate the commands that are being run silently by the installer)

It looks like [nquake.ini](https://raw.githubusercontent.com/nQuake/client-win32/master/etc/nquake.ini) points to the releases directory using `http` instead of `https`. Github will happily redirect you there:

```
% curl -I http://github.com/nQuake/distfiles/releases/download/snapshot/qsw106.zip
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Location: https://github.com/nQuake/distfiles/releases/download/snapshot/qsw106.zip
```

But because the `-L` flag is not specified, `curl` will not follow this redirect.

SOLUTIONS:

1. add `-L` to `curl` commands in the installer, or
2. update `nquake.ini` to use `https` URLs for mirrors.

**Comment by eb** [comment]
Yea, there's really no good reason to have the GitHub mirror specified as HTTP. Sure, wget would automatically follow the redirect to HTTPS (and that's why I haven't noticed the issue, because wget is used on Linux), but specifying the mirror as HTTPS in the nquake.ini file seems the proper solution to this. I've updated the nquake.ini file, it should work now as expected.

**Comment by eb** [comment]
Actually had to revert to HTTP again, since this change broke the installer scripts on macOS and Linux. I'll look into it.

**Comment by eb** [comment]
Ok, curl needs to follow redirects in any case if downloading from GitHub. So, now it's on https and additionally uses the -L option. Should now work as expected.

**Comment by dsandler** [comment]
Thanks! 👍
